### ISSUE TITLE
Is there are reason for the plugin to require maven >= 3.5.3?

### ISSUE THREAD

**Issue by MateuszStefek** [gantsign/ktlint-maven-plugin#192]
Can this plugin work on some older version of maven?

For example, a popular Ubuntu 18.04 LTS ships with maven 3.5.2 and many developers have this installed on default. I don't them spending time on upgrading.

**Comment by freemanjp** [comment]
@MateuszStefek thanks for raising this issue.

Maven 3.5.3 was the minimum version required by this plugin because it was the lowest Maven version I had tested with (it was also the version of Maven configured for [Maven Wrapper](https://github.com/takari/maven-wrapper) to use at the time the project was started so would be used by Travis CI to test the plugin).

I've reduced the minimum Maven version to 3.3.9 (this is the lowest Maven version installable using [SDKMAN!](https://sdkman.io/). The Travis CI build now tests against Maven 3.3.9 and 3.6.0.

You can find this change in version [0.9.21](https://github.com/gantsign/ktlint-maven-plugin/releases/tag/0.9.21) of this plugin.

**Comment by MateuszStefek** [comment]
Thanks for a quick fix! We will be using version 0.9.21. With this plugin, the build times are now 15 seconds faster, compared to ktlint executed via antrun.
