### ISSUE TITLE
The plugin should be marked as @threadSafe

### ISSUE THREAD

**Issue by MateuszStefek** [gantsign/ktlint-maven-plugin#195]
I don't think there's anything non-thread safe in a multi module build using this plugin. This warning is unnecessary:

[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in *****:
[WARNING] com.github.gantsign.maven:ktlint-maven-plugin:0.9.21

**Comment by freemanjp** [comment]
@MateuszStefek thanks for raising this issue.

Honestly, I was in two minds about changing this since the thread safety is dependent on a lot of code I didn't write. In the end I decided to make the change based on a limited inspection of the code and some manual testing on a multi-module project. The risk is also limited by the fact that few people actually use Maven's parallel build feature.

You can find this change in version [0.9.22](https://github.com/gantsign/ktlint-maven-plugin/releases/tag/0.9.22) of this plugin.

FYI: I also find the following `MAVEN_OPS` speed up Maven builds when running on the HotSpot JVM:

* `-XX:TieredStopAtLevel=1` turns off HotSpot code profiling and server level HotSpot native compilation.
* `-Xverify:none` turns off byte code verification, which is relatively safe for local development (not for CI/Prod).
