### ISSUE TITLE
Feature request: option to skip some rules

### ISSUE THREAD

**Issue by energister** [gantsign/ktlint-maven-plugin#275]
It seems that `ktlint-maven-plugin` doesn't have an option to disable some rules (`disabled_rules` analogue of the ktlint)

**Comment by freemanjp** [comment]
@energister thanks for raising this feature request.

It's true that this Maven plugin doesn't have a configuration parameter for `disabled_rules`. However, It does support `disabled_rules` in `.editorconfig` files in the same was as the [ktlint CLI](https://github.com/pinterest/ktlint#editorconfig).

Frankly, I think the `.editorconfig` files are a more appropriate place for this configuration than the Maven `pom.xml`. It also ensures other tools using `ktlint` use the same rules as Maven.

So unless you can provide a compelling use case for using a plugin configuration parameter instead of the `.editorconfig` file, I'm not inclined to implement this feature.
